language: go

go:
 - "1.12"  # 指定Golang 1.12

env:
 global:
  # Github Pages
  - GH_REF: github.com/wujunze/wujunze.github.io
  - HUGO_ENV: production

# Specify which branches to build using a safelist
# 分支白名单限制：只有 master 分支的提交才会触发构建
# branches:
#   only:
#     - master

before_install:
 # 安装 hugo
 - mkdir $HOME/src
 - cd $HOME/src
 - git clone https://github.com/gohugoio/hugo.git
 - cd hugo
 - go install

install:
 # 运行hugo命令
 - hugo

script:
 - cd ./public
 - git init
 - git config user.name "wujunze"
 - git config user.email "itwujunze@163.com"
 - git add .
 - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
 # Github Pages
 - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master