language: go

go:
  - "1.8"  # 指定Golang 1.8

env:
 global:
   # Github Pages
   - GH_REF: github.com/wujunze/wujunze.github.io
   - HUGO_ENV: production


install:
 # 安装最新的hugo
 - go get github.com/spf13/hugo

script:
  - hugo
  - cd ./public
  - git init
  - git config user.name "wujunze"
  - git config user.email "itwujunze@163.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://$GITHUB_TOKEN@${GH_REF}" master:master
